---
# =============================================================================
# Playbook: Podpięcie ISO i restart VM z bootem z CDROM
# =============================================================================
# Użycie:
#   ansible-playbook attach-iso.yml -e @clusters/ocp1.yml
#
# Wymagania:
#   - ISO wygenerowane przez generate-ocp-agent-iso.yml
#   - VM utworzone przez create-virt-env.yml
#
# Co robi:
#   1. Uploaduje ISO do PVC (jeśli nie istnieje)
#   2. Podpina CDROM do każdej VM
#   3. Ustawia boot order: CDROM pierwszy
#   4. Restartuje VM
# =============================================================================

- name: Podpięcie ISO i restart VM
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    install_dir: "/tmp/ocp-install/{{ cluster_name }}"
    iso_file: "{{ install_dir }}/agent.x86_64.iso"

  tasks:
    # =========================================================================
    # Krok 1: Walidacja
    # =========================================================================
    - name: "=== PODPINANIE ISO DLA KLASTRA {{ cluster_name }} ==="
      ansible.builtin.debug:
        msg: "Namespace: {{ namespace }}, Nodes: {{ nodes | length }}"

    - name: Sprawdź czy ISO istnieje
      ansible.builtin.stat:
        path: "{{ iso_file }}"
      register: iso_stat
      delegate_to: localhost

    - name: Błąd — brak ISO
      ansible.builtin.fail:
        msg: |
          Nie znaleziono ISO: {{ iso_file }}
          Najpierw uruchom: ansible-playbook generate-ocp-agent-iso.yml -e @clusters/{{ cluster_name }}.yml
      when: not iso_stat.stat.exists

    # =========================================================================
    # Krok 2: Sprawdź/utwórz PVC dla ISO
    # =========================================================================
    - name: Sprawdź czy PVC dla ISO istnieje
      kubernetes.core.k8s_info:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: "{{ namespace }}"
        name: "{{ iso_pvc_name }}"
      register: iso_pvc_info

    - name: "=== UPLOAD ISO DO PVC ==="
      ansible.builtin.debug:
        msg: "Uploaduję {{ iso_file }} do PVC {{ iso_pvc_name }}..."
      when: iso_pvc_info.resources | length == 0

    - name: Upload ISO do PVC przez virtctl
      ansible.builtin.command:
        cmd: >
          virtctl image-upload pvc {{ iso_pvc_name }}
          --size=2Gi
          --image-path={{ iso_file }}
          -n {{ namespace }}
          --insecure
      when: iso_pvc_info.resources | length == 0
      register: upload_result

    - name: Upload zakończony
      ansible.builtin.debug:
        msg: "ISO uploadowane do PVC {{ iso_pvc_name }}"
      when: iso_pvc_info.resources | length == 0

    - name: PVC już istnieje
      ansible.builtin.debug:
        msg: "PVC {{ iso_pvc_name }} już istnieje — pomijam upload"
      when: iso_pvc_info.resources | length > 0

    # =========================================================================
    # Krok 3: Zatrzymaj VM przed modyfikacją
    # =========================================================================
    - name: "=== ZATRZYMYWANIE VM ==="
      ansible.builtin.debug:
        msg: "Zatrzymuję VM przed dodaniem CDROM..."

    - name: Zatrzymaj VM
      kubernetes.core.k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ namespace }}"
        name: "{{ item.name }}"
        state: present
        merge_type: merge
        definition:
          spec:
            runStrategy: Halted
      loop: "{{ nodes }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Poczekaj na zatrzymanie VMI
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ namespace }}"
        name: "{{ item.name }}"
      register: vmi_check
      until: vmi_check.resources | length == 0
      retries: 30
      delay: 5
      loop: "{{ nodes }}"
      loop_control:
        label: "{{ item.name }}"

    # =========================================================================
    # Krok 4: Dodaj CDROM do VM
    # =========================================================================
    - name: "=== DODAWANIE CDROM ==="
      ansible.builtin.debug:
        msg: "Dodaję CDROM z ISO do VM..."

    - name: Dodaj CDROM disk i volume do VM (oc patch)
      ansible.builtin.command:
        cmd: >
          oc patch vm {{ item.name }} -n {{ namespace }} --type=json -p='[
            {"op": "replace", "path": "/spec/template/spec/domain/devices/disks", "value": [
              {"name": "rootdisk", "disk": {"bus": "virtio"}, "bootOrder": 2},
              {"name": "cdrom-iso", "cdrom": {"bus": "sata"}, "bootOrder": 1}
            ]},
            {"op": "replace", "path": "/spec/template/spec/volumes", "value": [
              {"name": "rootdisk", "dataVolume": {"name": "{{ item.name }}-rootdisk"}},
              {"name": "cdrom-iso", "persistentVolumeClaim": {"claimName": "{{ iso_pvc_name }}"}}
            ]}
          ]'
      loop: "{{ nodes }}"
      loop_control:
        label: "{{ item.name }}"
      register: patch_result
      changed_when: true

    # =========================================================================
    # Krok 5: Uruchom VM
    # =========================================================================
    - name: "=== URUCHAMIANIE VM ==="
      ansible.builtin.debug:
        msg: "Uruchamiam VM z bootem z CDROM..."

    - name: Uruchom VM
      kubernetes.core.k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ namespace }}"
        name: "{{ item.name }}"
        state: present
        merge_type: merge
        definition:
          spec:
            runStrategy: Always
      loop: "{{ nodes }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Poczekaj na uruchomienie VMI
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ namespace }}"
        name: "{{ item.name }}"
      register: vmi_status
      until: >
        vmi_status.resources | length > 0 and
        vmi_status.resources[0].status.phase | default('') == 'Running'
      retries: 60
      delay: 10
      loop: "{{ nodes }}"
      loop_control:
        label: "{{ item.name }}"

    # =========================================================================
    # Krok 6: Podsumowanie
    # =========================================================================
    - name: "=== SUKCES ==="
      ansible.builtin.debug:
        msg: |
          VM uruchomione z ISO!

          Następne kroki:
          1. Monitoruj instalację:
             ansible-playbook wait-ocp-install.yml -e @clusters/{{ cluster_name }}.yml

          2. Lub ręcznie:
             openshift-install agent wait-for install-complete --dir={{ install_dir }}

          3. Konsola VM:
             virtctl console {{ nodes[0].name }} -n {{ namespace }}
