---
# =============================================================================
# Playbook: Tworzenie maszyn wirtualnych dla środowiska
# =============================================================================
# Użycie:
#   ansible-playbook create-virt-env.yml -e @clusters/ocp1.yml
#
# Logika:
#   - Istniejące VM NIE są modyfikowane (nawet jeśli parametry się różnią)
#   - Tylko NOWE VM są tworzone z szablonu
#   - Po utworzeniu MAC adresy są zapisywane do pliku konfiguracyjnego
#   - Na końcu wyświetlane są informacje o VM i MAC adresach
# =============================================================================

- name: Tworzenie maszyn wirtualnych
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Ścieżka do pliku konfiguracyjnego (przekazana przez -e @clusters/xxx.yml)
    cluster_config_file: "{{ lookup('env', 'PWD') }}/clusters/{{ cluster_name }}.yml"

  tasks:
    # =========================================================================
    # Krok 1: Walidacja
    # =========================================================================
    - name: "=== TWORZENIE VM DLA KLASTRA {{ cluster_name }} ==="
      ansible.builtin.debug:
        msg: "Namespace: {{ namespace }}, Nodes: {{ nodes | length }}"

    # =========================================================================
    # Krok 2: Pobierz listę istniejących VM w namespace
    # =========================================================================
    - name: Pobierz listę istniejących VM
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ namespace }}"
      register: existing_vms

    - name: Zbuduj listę nazw istniejących VM
      ansible.builtin.set_fact:
        existing_vm_names: "{{ existing_vms.resources | map(attribute='metadata.name') | list }}"

    - name: Pokaż istniejące VM
      ansible.builtin.debug:
        msg: "Istniejące VM w namespace {{ namespace }}: {{ existing_vm_names }}"

    # =========================================================================
    # Krok 3: Filtruj tylko nowe VM (których jeszcze nie ma)
    # =========================================================================
    - name: Określ które VM trzeba utworzyć
      ansible.builtin.set_fact:
        vms_to_create: "{{ nodes | rejectattr('name', 'in', existing_vm_names) | list }}"

    - name: Pokaż VM do utworzenia
      ansible.builtin.debug:
        msg: "VM do utworzenia: {{ vms_to_create | map(attribute='name') | list }}"

    - name: Pokaż VM pominięte (już istnieją)
      ansible.builtin.debug:
        msg: "VM pominięte (już istnieją): {{ nodes | selectattr('name', 'in', existing_vm_names) | map(attribute='name') | list }}"

    # =========================================================================
    # Krok 4: Utwórz nowe VM z szablonu
    # =========================================================================
    - name: Utwórz nowe maszyny wirtualne
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'templates/vm-worker-large.yaml.j2') }}"
      vars:
        vm_name: "{{ item.name }}"
        vm_cpu_sockets: "{{ item.cpu_sockets | default(vm_defaults.cpu_sockets) }}"
        vm_memory: "{{ item.memory | default(vm_defaults.memory) }}"
        vm_disk_size: "{{ item.disk_size | default(vm_defaults.disk_size) }}"
        vm_max_cpu_sockets: "{{ item.max_cpu_sockets | default(vm_defaults.max_cpu_sockets) }}"
        vm_max_memory: "{{ item.max_memory | default(vm_defaults.max_memory) }}"
      loop: "{{ vms_to_create }}"
      loop_control:
        label: "{{ item.name }}"
      register: created_vms
      when: vms_to_create | length > 0

    # =========================================================================
    # Krok 5: Poczekaj na utworzenie DataVolumes (provisioning dysków)
    # =========================================================================
    - name: Poczekaj na zakończenie provisioningu DataVolumes
      kubernetes.core.k8s_info:
        api_version: cdi.kubevirt.io/v1beta1
        kind: DataVolume
        namespace: "{{ namespace }}"
        name: "{{ item.name }}-rootdisk"
      register: dv_status
      until: >
        dv_status.resources | length > 0 and
        (dv_status.resources[0].status.phase | default('') == 'Succeeded' or
         dv_status.resources[0].status.phase | default('') == 'WaitForFirstConsumer')
      retries: 30
      delay: 10
      loop: "{{ vms_to_create }}"
      loop_control:
        label: "{{ item.name }}-rootdisk"
      when: vms_to_create | length > 0

    # =========================================================================
    # Krok 6: Sprawdź czy VMI (instancje) się uruchomiły
    # =========================================================================
    - name: Poczekaj na uruchomienie VMI
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ namespace }}"
        name: "{{ item.name }}"
      register: vmi_status
      until: >
        vmi_status.resources | length > 0 and
        vmi_status.resources[0].status.phase | default('') == 'Running'
      retries: 60
      delay: 10
      loop: "{{ vms_to_create }}"
      loop_control:
        label: "{{ item.name }}"
      when: vms_to_create | length > 0

    - name: Walidacja — pokaż status utworzonych VM
      ansible.builtin.debug:
        msg: "VM {{ item.name }} uruchomiona pomyślnie (status: Running)"
      loop: "{{ vms_to_create }}"
      loop_control:
        label: "{{ item.name }}"
      when: vms_to_create | length > 0

    # =========================================================================
    # Krok 7: Zbierz MAC adresy ze wszystkich VM
    # =========================================================================
    - name: Pobierz informacje o VMI dla wszystkich nodów
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ namespace }}"
        name: "{{ item.name }}"
      loop: "{{ nodes }}"
      loop_control:
        label: "{{ item.name }}"
      register: all_vmis_info

    - name: Zbuduj mapę VM → MAC (vlan214)
      ansible.builtin.set_fact:
        vm_mac_map: >-
          {{
            vm_mac_map | default({}) | combine({
              item.item.name: (item.resources[0].status.interfaces | default([]) | selectattr('name', 'equalto', 'vlan214') | first | default({})).mac | default('')
            })
          }}
      loop: "{{ all_vmis_info.results }}"
      loop_control:
        label: "{{ item.item.name }}"
      when: item.resources | length > 0

    # =========================================================================
    # Krok 8: Podsumowanie VM i MAC adresów
    # =========================================================================
    - name: Pobierz informacje o wszystkich VM (spec)
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ namespace }}"
        name: "{{ item.name }}"
      loop: "{{ nodes }}"
      loop_control:
        label: "{{ item.name }}"
      register: all_vms_info

    - name: "=== PODSUMOWANIE MASZYN WIRTUALNYCH ==="
      ansible.builtin.debug:
        msg: >-
          {{ item.resources[0].metadata.name }} |
          CPU: {{ item.resources[0].spec.template.spec.domain.cpu.sockets | default('?') }} |
          RAM: {{ item.resources[0].spec.template.spec.domain.memory.guest | default('?') }} |
          MAC(vlan214): {{ vm_mac_map[item.resources[0].metadata.name] | default('brak') }}
      loop: "{{ all_vms_info.results }}"
      loop_control:
        label: "{{ item.resources[0].metadata.name | default('?') }}"
      when: item.resources | length > 0

    # =========================================================================
    # Krok 9: Zaktualizuj plik konfiguracyjny z MAC adresami
    # =========================================================================
    - name: Wczytaj aktualny plik konfiguracyjny
      ansible.builtin.slurp:
        src: "{{ cluster_config_file }}"
      register: config_file_content

    - name: Parsuj YAML
      ansible.builtin.set_fact:
        config_data: "{{ config_file_content.content | b64decode | from_yaml }}"

    - name: Zaktualizuj MAC adresy w konfiguracji
      ansible.builtin.set_fact:
        updated_nodes: >-
          {{
            config_data.nodes | map('combine', {
              'mac': vm_mac_map[item.name] | default(item.mac)
            }) | list
          }}
      vars:
        item: "{{ config_data.nodes }}"

    - name: Przygotuj zaktualizowaną konfigurację
      ansible.builtin.set_fact:
        updated_nodes_list: []

    - name: Buduj listę nodów z MAC
      ansible.builtin.set_fact:
        updated_nodes_list: "{{ updated_nodes_list + [item | combine({'mac': vm_mac_map[item.name] | default(item.mac)})] }}"
      loop: "{{ config_data.nodes }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Zapisz zaktualizowaną konfigurację
      ansible.builtin.copy:
        content: |
          # =============================================================================
          # Konfiguracja klastra: {{ cluster_name }}
          # =============================================================================
          # UWAGA: MAC adresy zostały uzupełnione automatycznie.
          # Sprawdź IP adresy przed uruchomieniem generate-ocp-agent-iso.yml
          # =============================================================================

          # -----------------------------------------------------------------------------
          # Klaster
          # -----------------------------------------------------------------------------
          cluster_name: {{ cluster_name }}
          base_domain: {{ base_domain }}

          # -----------------------------------------------------------------------------
          # VM - OpenShift Virtualization
          # -----------------------------------------------------------------------------
          namespace: {{ namespace }}
          iso_pvc_name: {{ iso_pvc_name }}
          multus_network: {{ multus_network }}

          vm_defaults:
            cpu_sockets: {{ vm_defaults.cpu_sockets }}
            memory: {{ vm_defaults.memory }}
            disk_size: {{ vm_defaults.disk_size }}
            max_cpu_sockets: {{ vm_defaults.max_cpu_sockets }}
            max_memory: {{ vm_defaults.max_memory }}

          # -----------------------------------------------------------------------------
          # Sieć
          # -----------------------------------------------------------------------------
          machine_network: {{ machine_network }}
          dns_server: {{ dns_server }}
          gateway: {{ gateway }}

          api_vip: {{ api_vip }}
          ingress_vip: {{ ingress_vip }}
          external_lb: {{ external_lb }}

          cluster_network_cidr: {{ cluster_network_cidr }}
          cluster_network_prefix: {{ cluster_network_prefix }}
          service_network_cidr: {{ service_network_cidr }}

          # -----------------------------------------------------------------------------
          # Nodes
          # -----------------------------------------------------------------------------
          nodes:
          {% for node in updated_nodes_list %}
            - name: {{ node.name }}
              hostname: {{ node.hostname }}
              role: {{ node.role }}
              mac: "{{ node.mac }}"
              ip: {{ node.ip }}
          {% endfor %}

          # -----------------------------------------------------------------------------
          # Opcje instalacji
          # -----------------------------------------------------------------------------
          single_node: {{ single_node }}
          fips_enabled: {{ fips_enabled }}
        dest: "{{ cluster_config_file }}"
        mode: '0644'

    - name: "=== PLIK KONFIGURACYJNY ZAKTUALIZOWANY ==="
      ansible.builtin.debug:
        msg: |
          MAC adresy zostały zapisane do: {{ cluster_config_file }}

          Następne kroki:
          1. Sprawdź/uzupełnij IP adresy w pliku {{ cluster_config_file }}
          2. Uruchom: ansible-playbook generate-ocp-agent-iso.yml -e @clusters/{{ cluster_name }}.yml

    - name: "=== TABELA NODÓW ==="
      ansible.builtin.debug:
        msg: "{{ item.name }} | {{ item.hostname }} | {{ item.role }} | MAC: {{ vm_mac_map[item.name] | default('brak') }} | IP: {{ item.ip }}"
      loop: "{{ nodes }}"
      loop_control:
        label: "{{ item.name }}"
