---
# =============================================================================
# Playbook: Zmiana boot order z CDROM na rootdisk
# =============================================================================
# Użycie:
#   ansible-playbook bootorder.yml -e @clusters/ocp1.yml
#
# Opcje:
#   -e restart=yes           # zatrzymaj i uruchom VM po zmianie (domyślnie: nie)
#   -e target_role=worker    # tylko nody o danej roli (master/worker/infra)
#   -e "target_nodes=['vm1','vm2']"  # tylko konkretne VM (lista nazw)
#
# Co robi:
#   1. Filtruje nody według target_role lub target_nodes (jeśli podano)
#   2. Sprawdza czy CDROM jest na pierwszym miejscu w boot order
#   3. Jeśli tak — zmienia na rootdisk pierwszy, CDROM drugi
#   4. Domyślnie NIE restartuje VM (zmiana zadziała przy następnym restarcie)
#   5. Z restart=yes — zatrzymuje i uruchamia VM
#
# Typowe użycie:
#   - W trakcie instalacji OCP: bez restart (node sam się zrestartuje)
#   - Po instalacji: z -e restart=yes
# =============================================================================

- name: Zmiana boot order na rootdisk
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    restart: false
    target_role: ""
    target_nodes: []

  tasks:
    # =========================================================================
    # Krok 1: Filtrowanie nodów
    # =========================================================================
    - name: Filtruj nody według target_role
      ansible.builtin.set_fact:
        filtered_nodes: "{{ nodes | selectattr('role', 'equalto', target_role) | list }}"
      when: target_role | length > 0

    - name: Filtruj nody według target_nodes
      ansible.builtin.set_fact:
        filtered_nodes: "{{ nodes | selectattr('name', 'in', target_nodes) | list }}"
      when:
        - target_role | length == 0
        - target_nodes | length > 0

    - name: Użyj wszystkich nodów (brak filtra)
      ansible.builtin.set_fact:
        filtered_nodes: "{{ nodes }}"
      when:
        - target_role | length == 0
        - target_nodes | length == 0

    - name: "=== ZMIANA BOOT ORDER DLA KLASTRA {{ cluster_name }} ==="
      ansible.builtin.debug:
        msg: |
          Namespace: {{ namespace }}, Restart: {{ restart }}
          {% if target_role | length > 0 %}Filtr: role={{ target_role }}{% elif target_nodes | length > 0 %}Filtr: {{ target_nodes }}{% else %}Filtr: wszystkie{% endif %}
          Nody ({{ filtered_nodes | length }}): {{ filtered_nodes | map(attribute='name') | list }}

    # =========================================================================
    # Krok 2: Sprawdź aktualny boot order
    # =========================================================================
    - name: Pobierz definicje VM
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ namespace }}"
        name: "{{ item.name }}"
      loop: "{{ filtered_nodes }}"
      loop_control:
        label: "{{ item.name }}"
      register: vm_info

    - name: Sprawdź boot order dla każdej VM
      ansible.builtin.set_fact:
        vms_with_cdrom_first: >-
          {{ vms_with_cdrom_first | default([]) + (
            [item.item.name] if (
              item.resources | length > 0 and
              item.resources[0].spec.template.spec.domain.devices.disks | default([]) | selectattr('name', 'equalto', 'cdrom-iso') | list | length > 0 and
              (item.resources[0].spec.template.spec.domain.devices.disks | selectattr('name', 'equalto', 'cdrom-iso') | first).bootOrder | default(99) == 1
            ) else []
          ) }}
      loop: "{{ vm_info.results }}"
      loop_control:
        label: "{{ item.item.name }}"

    - name: Pokaż VM z CDROM jako pierwszy boot
      ansible.builtin.debug:
        msg: "VM z CDROM na pierwszym miejscu: {{ vms_with_cdrom_first | default([]) }}"

    - name: Brak VM do zmiany
      ansible.builtin.debug:
        msg: "Wszystkie VM mają już rootdisk jako pierwszy boot. Nic do zmiany."
      when: vms_with_cdrom_first | default([]) | length == 0

    # =========================================================================
    # Krok 3: Zatrzymaj VM (tylko gdy restart=yes)
    # =========================================================================
    - name: "=== ZATRZYMYWANIE VM ==="
      ansible.builtin.debug:
        msg: "Zatrzymuję VM przed zmianą boot order..."
      when:
        - vms_with_cdrom_first | default([]) | length > 0
        - restart | bool

    - name: Zatrzymaj VM
      kubernetes.core.k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ namespace }}"
        name: "{{ item }}"
        state: present
        merge_type: merge
        definition:
          spec:
            runStrategy: Halted
      loop: "{{ vms_with_cdrom_first | default([]) }}"
      loop_control:
        label: "{{ item }}"
      when:
        - vms_with_cdrom_first | default([]) | length > 0
        - restart | bool

    - name: Poczekaj na zatrzymanie VMI
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ namespace }}"
        name: "{{ item }}"
      register: vmi_check
      until: vmi_check.resources | length == 0
      retries: 30
      delay: 5
      loop: "{{ vms_with_cdrom_first | default([]) }}"
      loop_control:
        label: "{{ item }}"
      when:
        - vms_with_cdrom_first | default([]) | length > 0
        - restart | bool

    # =========================================================================
    # Krok 4: Zmień boot order (oc patch)
    # =========================================================================
    - name: "=== ZMIANA BOOT ORDER ==="
      ansible.builtin.debug:
        msg: "Zmieniam boot order: rootdisk=1, cdrom=2..."
      when: vms_with_cdrom_first | default([]) | length > 0

    - name: Zmień boot order (oc patch)
      ansible.builtin.command:
        cmd: >
          oc patch vm {{ item }} -n {{ namespace }} --type=json -p='[
            {"op": "replace", "path": "/spec/template/spec/domain/devices/disks", "value": [
              {"name": "rootdisk", "disk": {"bus": "virtio"}, "bootOrder": 1},
              {"name": "cdrom-iso", "cdrom": {"bus": "sata"}, "bootOrder": 2}
            ]}
          ]'
      loop: "{{ vms_with_cdrom_first | default([]) }}"
      loop_control:
        label: "{{ item }}"
      register: patch_result
      changed_when: true
      when: vms_with_cdrom_first | default([]) | length > 0

    # =========================================================================
    # Krok 5: Uruchom VM (tylko gdy restart=yes)
    # =========================================================================
    - name: "=== URUCHAMIANIE VM ==="
      ansible.builtin.debug:
        msg: "Uruchamiam VM z bootem z rootdisk..."
      when:
        - vms_with_cdrom_first | default([]) | length > 0
        - restart | bool

    - name: Uruchom VM
      kubernetes.core.k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ namespace }}"
        name: "{{ item }}"
        state: present
        merge_type: merge
        definition:
          spec:
            runStrategy: Always
      loop: "{{ vms_with_cdrom_first | default([]) }}"
      loop_control:
        label: "{{ item }}"
      when:
        - vms_with_cdrom_first | default([]) | length > 0
        - restart | bool

    - name: Poczekaj na uruchomienie VMI
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ namespace }}"
        name: "{{ item }}"
      register: vmi_status
      until: >
        vmi_status.resources | length > 0 and
        vmi_status.resources[0].status.phase | default('') == 'Running'
      retries: 60
      delay: 10
      loop: "{{ vms_with_cdrom_first | default([]) }}"
      loop_control:
        label: "{{ item }}"
      when:
        - vms_with_cdrom_first | default([]) | length > 0
        - restart | bool

    # =========================================================================
    # Krok 6: Podsumowanie
    # =========================================================================
    - name: "=== SUKCES ==="
      ansible.builtin.debug:
        msg: |
          Boot order zmieniony pomyślnie!

          VM ze zmienionym boot order: {{ vms_with_cdrom_first | default([]) | join(', ') }}
          Nowy boot order: 1. rootdisk, 2. cdrom
          {% if restart | bool %}
          VM zostały zrestartowane.
          {% else %}
          VM NIE zostały zrestartowane - zmiana zadziała przy następnym restarcie.
          Aby zrestartować teraz: ansible-playbook bootorder.yml -e @clusters/{{ cluster_name }}.yml -e restart=yes
          {% endif %}
      when: vms_with_cdrom_first | default([]) | length > 0
